name: flutter_blackjack
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter_localizations:
      sdk: flutter
  flutter:
    sdk: flutter    
  json_annotation:
  json_serializable:
  build_runner: 
  cupertino_icons:
  flutter_modular: 
  dio:
  get: 
  skeleton_text:
  cached_network_image: 
  equatable: 
  mocktail: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
